-- 코드를 입력하세요
# SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(DATETIME) AS COUNT
# FROM ANIMAL_OUTS
# WHERE DATE_FORMAT(DATETIME, '09') <= DATE_FORMAT(DATETIME, '%H') 
# AND DATE_FORMAT(DATETIME, '%H') < DATE_FORMAT(DATETIME, '20')
# GROUP BY HOUR
# ORDER BY HOUR;


-- 코드를 입력하세요
SELECT HOUR, COUNT(HOUR) FROM
(SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR FROM ANIMAL_OUTS) H
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR
