-- 코드를 작성해주세요
-- 1번 풀이
SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D 
JOIN SKILLCODES AS S ON D.SKILL_CODE & S.CODE
WHERE NAME = 'C#' OR NAME = 'Python'
ORDER BY ID ASC;

-- 2번 풀이
# SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE SKILL_CODE & 256 > 0  -- Python 스킬 보유 여부 확인
#    OR SKILL_CODE & 1024 > 0  -- C# 스킬 보유 여부 확인
# ORDER BY ID ASC;
