-- 코드를 작성해주세요
SELECT DISTINCT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
INNER JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH IN (
    SELECT MAX(LENGTH)
    FROM FISH_INFO AS A2
    WHERE A2.FISH_TYPE = A.FISH_TYPE
)
AND A.LENGTH IS NOT NULL AND A.LENGTH > 10
ORDER BY A.ID;