-- 코드를 작성해주세요
SELECT DISTINCT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
INNER JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
# 서브쿼리: 각 FISH_TYPE별로 가장 큰 LENGTH를 찾아 WHERE절에서 해당 값과 비교
WHERE A.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO AS A2
    WHERE A2.FISH_TYPE = A.FISH_TYPE
    # 종류 별로 가장 큰 물고기를 찾기 위해 A.FISH_TYPE = A2.FISH_TYPE 조건으로 MAX(LENGTH)와 비교
)
AND A.LENGTH IS NOT NULL AND A.LENGTH > 10
ORDER BY A.ID;